//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shmzh.Monitor.Data.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/Shmzh.Monitor.DataService/RunStatus.asmx")]
        public string Shmzh_Monitor_Data_RunStatusService_RunStatus {
            get {
                return ((string)(this["Shmzh_Monitor_Data_RunStatusService_RunStatus"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/Shmzh.Monitor.DataService/TagDay.asmx")]
        public string Shmzh_Monitor_Data_TagDayService_TagDay {
            get {
                return ((string)(this["Shmzh_Monitor_Data_TagDayService_TagDay"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/Shmzh.Monitor.DataService/TagHour.asmx")]
        public string Shmzh_Monitor_Data_TagHourService_TagHour {
            get {
                return ((string)(this["Shmzh_Monitor_Data_TagHourService_TagHour"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/Shmzh.Monitor.DataService/Tag.asmx")]
        public string Shmzh_Monitor_Data_TagService_Tag {
            get {
                return ((string)(this["Shmzh_Monitor_Data_TagService_Tag"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/Shmzh.Monitor.DataService/TagMinute.asmx")]
        public string Shmzh_Monitor_Data_TagMinuteService_TagMinute {
            get {
                return ((string)(this["Shmzh_Monitor_Data_TagMinuteService_TagMinute"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/Shmzh.Monitor.DataService/TagMin15.asmx")]
        public string Shmzh_Monitor_Data_TagMin15Service_TagMin15 {
            get {
                return ((string)(this["Shmzh_Monitor_Data_TagMin15Service_TagMin15"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/Shmzh.Monitor.DataService/TagMonth.asmx")]
        public string Shmzh_Monitor_Data_TagMonthService_TagMonth {
            get {
                return ((string)(this["Shmzh_Monitor_Data_TagMonthService_TagMonth"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/Shmzh.Monitor.DataService/TagYear.asmx")]
        public string Shmzh_Monitor_Data_TagYearService_TagYear {
            get {
                return ((string)(this["Shmzh_Monitor_Data_TagYearService_TagYear"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/Shmzh.Monitor.DataService/TagSecond.asmx")]
        public string Shmzh_Monitor_Data_TagSecondService_TagSecond {
            get {
                return ((string)(this["Shmzh_Monitor_Data_TagSecondService_TagSecond"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/Shmzh.Monitor.DataService/FloatingBlock.asmx")]
        public string Shmzh_Monitor_Data_FloatingBlock_FloatingBlock {
            get {
                return ((string)(this["Shmzh_Monitor_Data_FloatingBlock_FloatingBlock"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/shmzh.monitor.dataservice/FloatingBlockItem.asmx")]
        public string Shmzh_Monitor_Data_FloatingBlockItem_FloatingBlockItem {
            get {
                return ((string)(this["Shmzh_Monitor_Data_FloatingBlockItem_FloatingBlockItem"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/shmzh.monitor.dataservice/graphschemaItem.asmx")]
        public string Shmzh_Monitor_Data_GraphSchemaItem_GraphSchemaItem {
            get {
                return ((string)(this["Shmzh_Monitor_Data_GraphSchemaItem_GraphSchemaItem"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/shmzh.monitor.dataservice/graphschemartag.asmx")]
        public string Shmzh_Monitor_Data_GraphSchemaRTag_GraphSchemaRTag {
            get {
                return ((string)(this["Shmzh_Monitor_Data_GraphSchemaRTag_GraphSchemaRTag"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/shmzh.monitor.dataservice/GraphSchemaTab.asmx")]
        public string Shmzh_Monitor_Data_GraphSchemaTab_GraphSchemaTab {
            get {
                return ((string)(this["Shmzh_Monitor_Data_GraphSchemaTab_GraphSchemaTab"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/shmzh.monitor.dataservice/graphschematag.asmx")]
        public string Shmzh_Monitor_Data_GraphSchemaTag_GraphSchemaTag {
            get {
                return ((string)(this["Shmzh_Monitor_Data_GraphSchemaTag_GraphSchemaTag"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/shmzh.monitor.dataservice/monitorobj.asmx")]
        public string Shmzh_Monitor_Data_MonitorObj_MonitorObj {
            get {
                return ((string)(this["Shmzh_Monitor_Data_MonitorObj_MonitorObj"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/shmzh.monitor.dataservice/objtype.asmx")]
        public string Shmzh_Monitor_Data_ObjType_ObjType {
            get {
                return ((string)(this["Shmzh_Monitor_Data_ObjType_ObjType"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/shmzh.monitor.dataservice/objtypeattr.asmx")]
        public string Shmzh_Monitor_Data_ObjTypeAttrService_ObjTypeAttr {
            get {
                return ((string)(this["Shmzh_Monitor_Data_ObjTypeAttrService_ObjTypeAttr"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/Shmzh.Monitor.DataService/TagGather.asmx")]
        public string Shmzh_Monitor_Data_TagGatherService_TagGather {
            get {
                return ((string)(this["Shmzh_Monitor_Data_TagGatherService_TagGather"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/Shmzh.Monitor.DataService/GraphSchema.asmx")]
        public string Shmzh_Monitor_Data_GraphSchemaService_GraphSchema {
            get {
                return ((string)(this["Shmzh_Monitor_Data_GraphSchemaService_GraphSchema"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/Shmzh.Monitor.DataService/Category.asmx")]
        public string Shmzh_Monitor_Data_CategoryService_Category {
            get {
                return ((string)(this["Shmzh_Monitor_Data_CategoryService_Category"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/Shmzh.Monitor.DataService/CategoryItem.asmx")]
        public string Shmzh_Monitor_Data_CategoryItemService_CategoryItem {
            get {
                return ((string)(this["Shmzh_Monitor_Data_CategoryItemService_CategoryItem"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/Shmzh.Monitor.DataService/TagCategory.asmx")]
        public string Shmzh_Monitor_Data_TagCategoryService_TagCategory {
            get {
                return ((string)(this["Shmzh_Monitor_Data_TagCategoryService_TagCategory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/Shmzh.Monitor.DataService/TagCategoryDetail.asmx")]
        public string Shmzh_Monitor_Data_TagCategoryDetailService_TagCategoryDetail {
            get {
                return ((string)(this["Shmzh_Monitor_Data_TagCategoryDetailService_TagCategoryDetail"]));
            }
        }
    }
}
