//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.18444 版自动生成。
// 
#pragma warning disable 1591

namespace Shmzh.Monitor.Data.TagService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TagSoap", Namespace="http://shuizhi.ypwater.org/DataService/")]
    public partial class Tag : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllOperationCompleted;
        
        private System.Threading.SendOrPostCallback QuickSearchOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetByType_TagId_TagNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get3TagEligibleRateOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get4TagEligibleRateOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get7TagEligibleRateOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Tag() {
            this.Url = global::Shmzh.Monitor.Data.Properties.Settings.Default.Shmzh_Monitor_Data_TagService_Tag;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetByIdCompletedEventHandler GetByIdCompleted;
        
        /// <remarks/>
        public event GetAllCompletedEventHandler GetAllCompleted;
        
        /// <remarks/>
        public event QuickSearchCompletedEventHandler QuickSearchCompleted;
        
        /// <remarks/>
        public event GetByType_TagId_TagNameCompletedEventHandler GetByType_TagId_TagNameCompleted;
        
        /// <remarks/>
        public event GetDateCompletedEventHandler GetDateCompleted;
        
        /// <remarks/>
        public event Get3TagEligibleRateCompletedEventHandler Get3TagEligibleRateCompleted;
        
        /// <remarks/>
        public event Get4TagEligibleRateCompletedEventHandler Get4TagEligibleRateCompleted;
        
        /// <remarks/>
        public event Get7TagEligibleRateCompletedEventHandler Get7TagEligibleRateCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://shuizhi.ypwater.org/DataService/GetById", RequestNamespace="http://shuizhi.ypwater.org/DataService/", ResponseNamespace="http://shuizhi.ypwater.org/DataService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TagInfo GetById(string tagId) {
            object[] results = this.Invoke("GetById", new object[] {
                        tagId});
            return ((TagInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetByIdAsync(string tagId) {
            this.GetByIdAsync(tagId, null);
        }
        
        /// <remarks/>
        public void GetByIdAsync(string tagId, object userState) {
            if ((this.GetByIdOperationCompleted == null)) {
                this.GetByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetByIdOperationCompleted);
            }
            this.InvokeAsync("GetById", new object[] {
                        tagId}, this.GetByIdOperationCompleted, userState);
        }
        
        private void OnGetByIdOperationCompleted(object arg) {
            if ((this.GetByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetByIdCompleted(this, new GetByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://shuizhi.ypwater.org/DataService/GetAll", RequestNamespace="http://shuizhi.ypwater.org/DataService/", ResponseNamespace="http://shuizhi.ypwater.org/DataService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TagInfo[] GetAll() {
            object[] results = this.Invoke("GetAll", new object[0]);
            return ((TagInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllAsync() {
            this.GetAllAsync(null);
        }
        
        /// <remarks/>
        public void GetAllAsync(object userState) {
            if ((this.GetAllOperationCompleted == null)) {
                this.GetAllOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllOperationCompleted);
            }
            this.InvokeAsync("GetAll", new object[0], this.GetAllOperationCompleted, userState);
        }
        
        private void OnGetAllOperationCompleted(object arg) {
            if ((this.GetAllCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllCompleted(this, new GetAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://shuizhi.ypwater.org/DataService/QuickSearch", RequestNamespace="http://shuizhi.ypwater.org/DataService/", ResponseNamespace="http://shuizhi.ypwater.org/DataService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TagInfo[] QuickSearch(string strCondition) {
            object[] results = this.Invoke("QuickSearch", new object[] {
                        strCondition});
            return ((TagInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void QuickSearchAsync(string strCondition) {
            this.QuickSearchAsync(strCondition, null);
        }
        
        /// <remarks/>
        public void QuickSearchAsync(string strCondition, object userState) {
            if ((this.QuickSearchOperationCompleted == null)) {
                this.QuickSearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQuickSearchOperationCompleted);
            }
            this.InvokeAsync("QuickSearch", new object[] {
                        strCondition}, this.QuickSearchOperationCompleted, userState);
        }
        
        private void OnQuickSearchOperationCompleted(object arg) {
            if ((this.QuickSearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QuickSearchCompleted(this, new QuickSearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://shuizhi.ypwater.org/DataService/GetByType_TagId_TagName", RequestNamespace="http://shuizhi.ypwater.org/DataService/", ResponseNamespace="http://shuizhi.ypwater.org/DataService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TagInfo[] GetByType_TagId_TagName(string tagType, string tagId, string tagName) {
            object[] results = this.Invoke("GetByType_TagId_TagName", new object[] {
                        tagType,
                        tagId,
                        tagName});
            return ((TagInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetByType_TagId_TagNameAsync(string tagType, string tagId, string tagName) {
            this.GetByType_TagId_TagNameAsync(tagType, tagId, tagName, null);
        }
        
        /// <remarks/>
        public void GetByType_TagId_TagNameAsync(string tagType, string tagId, string tagName, object userState) {
            if ((this.GetByType_TagId_TagNameOperationCompleted == null)) {
                this.GetByType_TagId_TagNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetByType_TagId_TagNameOperationCompleted);
            }
            this.InvokeAsync("GetByType_TagId_TagName", new object[] {
                        tagType,
                        tagId,
                        tagName}, this.GetByType_TagId_TagNameOperationCompleted, userState);
        }
        
        private void OnGetByType_TagId_TagNameOperationCompleted(object arg) {
            if ((this.GetByType_TagId_TagNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetByType_TagId_TagNameCompleted(this, new GetByType_TagId_TagNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://shuizhi.ypwater.org/DataService/GetDate", RequestNamespace="http://shuizhi.ypwater.org/DataService/", ResponseNamespace="http://shuizhi.ypwater.org/DataService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.DateTime GetDate() {
            object[] results = this.Invoke("GetDate", new object[0]);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public void GetDateAsync() {
            this.GetDateAsync(null);
        }
        
        /// <remarks/>
        public void GetDateAsync(object userState) {
            if ((this.GetDateOperationCompleted == null)) {
                this.GetDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDateOperationCompleted);
            }
            this.InvokeAsync("GetDate", new object[0], this.GetDateOperationCompleted, userState);
        }
        
        private void OnGetDateOperationCompleted(object arg) {
            if ((this.GetDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDateCompleted(this, new GetDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://shuizhi.ypwater.org/DataService/Get3TagEligibleRate", RequestNamespace="http://shuizhi.ypwater.org/DataService/", ResponseNamespace="http://shuizhi.ypwater.org/DataService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double Get3TagEligibleRate(System.DateTime beginDate, System.DateTime endDate) {
            object[] results = this.Invoke("Get3TagEligibleRate", new object[] {
                        beginDate,
                        endDate});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void Get3TagEligibleRateAsync(System.DateTime beginDate, System.DateTime endDate) {
            this.Get3TagEligibleRateAsync(beginDate, endDate, null);
        }
        
        /// <remarks/>
        public void Get3TagEligibleRateAsync(System.DateTime beginDate, System.DateTime endDate, object userState) {
            if ((this.Get3TagEligibleRateOperationCompleted == null)) {
                this.Get3TagEligibleRateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet3TagEligibleRateOperationCompleted);
            }
            this.InvokeAsync("Get3TagEligibleRate", new object[] {
                        beginDate,
                        endDate}, this.Get3TagEligibleRateOperationCompleted, userState);
        }
        
        private void OnGet3TagEligibleRateOperationCompleted(object arg) {
            if ((this.Get3TagEligibleRateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get3TagEligibleRateCompleted(this, new Get3TagEligibleRateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://shuizhi.ypwater.org/DataService/Get4TagEligibleRate", RequestNamespace="http://shuizhi.ypwater.org/DataService/", ResponseNamespace="http://shuizhi.ypwater.org/DataService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double Get4TagEligibleRate(System.DateTime beginDate, System.DateTime endDate) {
            object[] results = this.Invoke("Get4TagEligibleRate", new object[] {
                        beginDate,
                        endDate});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void Get4TagEligibleRateAsync(System.DateTime beginDate, System.DateTime endDate) {
            this.Get4TagEligibleRateAsync(beginDate, endDate, null);
        }
        
        /// <remarks/>
        public void Get4TagEligibleRateAsync(System.DateTime beginDate, System.DateTime endDate, object userState) {
            if ((this.Get4TagEligibleRateOperationCompleted == null)) {
                this.Get4TagEligibleRateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet4TagEligibleRateOperationCompleted);
            }
            this.InvokeAsync("Get4TagEligibleRate", new object[] {
                        beginDate,
                        endDate}, this.Get4TagEligibleRateOperationCompleted, userState);
        }
        
        private void OnGet4TagEligibleRateOperationCompleted(object arg) {
            if ((this.Get4TagEligibleRateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get4TagEligibleRateCompleted(this, new Get4TagEligibleRateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://shuizhi.ypwater.org/DataService/Get7TagEligibleRate", RequestNamespace="http://shuizhi.ypwater.org/DataService/", ResponseNamespace="http://shuizhi.ypwater.org/DataService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double Get7TagEligibleRate(System.DateTime beginDate, System.DateTime endDate) {
            object[] results = this.Invoke("Get7TagEligibleRate", new object[] {
                        beginDate,
                        endDate});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void Get7TagEligibleRateAsync(System.DateTime beginDate, System.DateTime endDate) {
            this.Get7TagEligibleRateAsync(beginDate, endDate, null);
        }
        
        /// <remarks/>
        public void Get7TagEligibleRateAsync(System.DateTime beginDate, System.DateTime endDate, object userState) {
            if ((this.Get7TagEligibleRateOperationCompleted == null)) {
                this.Get7TagEligibleRateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet7TagEligibleRateOperationCompleted);
            }
            this.InvokeAsync("Get7TagEligibleRate", new object[] {
                        beginDate,
                        endDate}, this.Get7TagEligibleRateOperationCompleted, userState);
        }
        
        private void OnGet7TagEligibleRateOperationCompleted(object arg) {
            if ((this.Get7TagEligibleRateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get7TagEligibleRateCompleted(this, new Get7TagEligibleRateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://shuizhi.ypwater.org/DataService/")]
    public partial class TagInfo {
        
        private string i_Tag_IdField;
        
        private string i_Tag_NameField;
        
        private int i_Dig_NumField;
        
        private string i_UnitField;
        
        private string i_Tag_TypeField;
        
        private int calc_Type_Before_HourField;
        
        private int calc_Type_After_HourField;
        
        private bool second_To_MinuteField;
        
        private bool minute_To_Min5Field;
        
        private bool minute_To_HourField;
        
        private bool hour_To_DayField;
        
        private bool day_To_MonthField;
        
        private bool month_To_YearField;
        
        private string remarkField;
        
        private string funcField;
        
        private string dev_CodeField;
        
        private double max_ValueField;
        
        private double min_ValueField;
        
        /// <remarks/>
        public string I_Tag_Id {
            get {
                return this.i_Tag_IdField;
            }
            set {
                this.i_Tag_IdField = value;
            }
        }
        
        /// <remarks/>
        public string I_Tag_Name {
            get {
                return this.i_Tag_NameField;
            }
            set {
                this.i_Tag_NameField = value;
            }
        }
        
        /// <remarks/>
        public int I_Dig_Num {
            get {
                return this.i_Dig_NumField;
            }
            set {
                this.i_Dig_NumField = value;
            }
        }
        
        /// <remarks/>
        public string I_Unit {
            get {
                return this.i_UnitField;
            }
            set {
                this.i_UnitField = value;
            }
        }
        
        /// <remarks/>
        public string I_Tag_Type {
            get {
                return this.i_Tag_TypeField;
            }
            set {
                this.i_Tag_TypeField = value;
            }
        }
        
        /// <remarks/>
        public int Calc_Type_Before_Hour {
            get {
                return this.calc_Type_Before_HourField;
            }
            set {
                this.calc_Type_Before_HourField = value;
            }
        }
        
        /// <remarks/>
        public int Calc_Type_After_Hour {
            get {
                return this.calc_Type_After_HourField;
            }
            set {
                this.calc_Type_After_HourField = value;
            }
        }
        
        /// <remarks/>
        public bool Second_To_Minute {
            get {
                return this.second_To_MinuteField;
            }
            set {
                this.second_To_MinuteField = value;
            }
        }
        
        /// <remarks/>
        public bool Minute_To_Min5 {
            get {
                return this.minute_To_Min5Field;
            }
            set {
                this.minute_To_Min5Field = value;
            }
        }
        
        /// <remarks/>
        public bool Minute_To_Hour {
            get {
                return this.minute_To_HourField;
            }
            set {
                this.minute_To_HourField = value;
            }
        }
        
        /// <remarks/>
        public bool Hour_To_Day {
            get {
                return this.hour_To_DayField;
            }
            set {
                this.hour_To_DayField = value;
            }
        }
        
        /// <remarks/>
        public bool Day_To_Month {
            get {
                return this.day_To_MonthField;
            }
            set {
                this.day_To_MonthField = value;
            }
        }
        
        /// <remarks/>
        public bool Month_To_Year {
            get {
                return this.month_To_YearField;
            }
            set {
                this.month_To_YearField = value;
            }
        }
        
        /// <remarks/>
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
        
        /// <remarks/>
        public string Func {
            get {
                return this.funcField;
            }
            set {
                this.funcField = value;
            }
        }
        
        /// <remarks/>
        public string Dev_Code {
            get {
                return this.dev_CodeField;
            }
            set {
                this.dev_CodeField = value;
            }
        }
        
        /// <remarks/>
        public double Max_Value {
            get {
                return this.max_ValueField;
            }
            set {
                this.max_ValueField = value;
            }
        }
        
        /// <remarks/>
        public double Min_Value {
            get {
                return this.min_ValueField;
            }
            set {
                this.min_ValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetByIdCompletedEventHandler(object sender, GetByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TagInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TagInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetAllCompletedEventHandler(object sender, GetAllCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TagInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TagInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void QuickSearchCompletedEventHandler(object sender, QuickSearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QuickSearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QuickSearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TagInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TagInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetByType_TagId_TagNameCompletedEventHandler(object sender, GetByType_TagId_TagNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetByType_TagId_TagNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetByType_TagId_TagNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TagInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TagInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetDateCompletedEventHandler(object sender, GetDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.DateTime Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void Get3TagEligibleRateCompletedEventHandler(object sender, Get3TagEligibleRateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get3TagEligibleRateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get3TagEligibleRateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void Get4TagEligibleRateCompletedEventHandler(object sender, Get4TagEligibleRateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get4TagEligibleRateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get4TagEligibleRateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void Get7TagEligibleRateCompletedEventHandler(object sender, Get7TagEligibleRateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get7TagEligibleRateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get7TagEligibleRateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591