//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.18444 版自动生成。
// 
#pragma warning disable 1591

namespace Shmzh.Monitor.Data.TagSecondService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TagSecondSoap", Namespace="http://service.ypwater.com/")]
    public partial class TagSecond : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Get_Latest_By_TagIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_Latest_By_TagIdsOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_Latest_AllOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TagSecond() {
            this.Url = global::Shmzh.Monitor.Data.Properties.Settings.Default.Shmzh_Monitor_Data_TagSecondService_TagSecond;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Get_Latest_By_TagIdCompletedEventHandler Get_Latest_By_TagIdCompleted;
        
        /// <remarks/>
        public event Get_Latest_By_TagIdsCompletedEventHandler Get_Latest_By_TagIdsCompleted;
        
        /// <remarks/>
        public event Get_Latest_AllCompletedEventHandler Get_Latest_AllCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.ypwater.com/Get_Latest_By_TagId", RequestNamespace="http://service.ypwater.com/", ResponseNamespace="http://service.ypwater.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TagSecondInfo Get_Latest_By_TagId(string tagId) {
            object[] results = this.Invoke("Get_Latest_By_TagId", new object[] {
                        tagId});
            return ((TagSecondInfo)(results[0]));
        }
        
        /// <remarks/>
        public void Get_Latest_By_TagIdAsync(string tagId) {
            this.Get_Latest_By_TagIdAsync(tagId, null);
        }
        
        /// <remarks/>
        public void Get_Latest_By_TagIdAsync(string tagId, object userState) {
            if ((this.Get_Latest_By_TagIdOperationCompleted == null)) {
                this.Get_Latest_By_TagIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_Latest_By_TagIdOperationCompleted);
            }
            this.InvokeAsync("Get_Latest_By_TagId", new object[] {
                        tagId}, this.Get_Latest_By_TagIdOperationCompleted, userState);
        }
        
        private void OnGet_Latest_By_TagIdOperationCompleted(object arg) {
            if ((this.Get_Latest_By_TagIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_Latest_By_TagIdCompleted(this, new Get_Latest_By_TagIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.ypwater.com/Get_Latest_By_TagIds", RequestNamespace="http://service.ypwater.com/", ResponseNamespace="http://service.ypwater.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TagSecondInfo[] Get_Latest_By_TagIds(string tagIds) {
            object[] results = this.Invoke("Get_Latest_By_TagIds", new object[] {
                        tagIds});
            return ((TagSecondInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void Get_Latest_By_TagIdsAsync(string tagIds) {
            this.Get_Latest_By_TagIdsAsync(tagIds, null);
        }
        
        /// <remarks/>
        public void Get_Latest_By_TagIdsAsync(string tagIds, object userState) {
            if ((this.Get_Latest_By_TagIdsOperationCompleted == null)) {
                this.Get_Latest_By_TagIdsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_Latest_By_TagIdsOperationCompleted);
            }
            this.InvokeAsync("Get_Latest_By_TagIds", new object[] {
                        tagIds}, this.Get_Latest_By_TagIdsOperationCompleted, userState);
        }
        
        private void OnGet_Latest_By_TagIdsOperationCompleted(object arg) {
            if ((this.Get_Latest_By_TagIdsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_Latest_By_TagIdsCompleted(this, new Get_Latest_By_TagIdsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.ypwater.com/Get_Latest_All", RequestNamespace="http://service.ypwater.com/", ResponseNamespace="http://service.ypwater.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TagSecondInfo[] Get_Latest_All() {
            object[] results = this.Invoke("Get_Latest_All", new object[0]);
            return ((TagSecondInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void Get_Latest_AllAsync() {
            this.Get_Latest_AllAsync(null);
        }
        
        /// <remarks/>
        public void Get_Latest_AllAsync(object userState) {
            if ((this.Get_Latest_AllOperationCompleted == null)) {
                this.Get_Latest_AllOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_Latest_AllOperationCompleted);
            }
            this.InvokeAsync("Get_Latest_All", new object[0], this.Get_Latest_AllOperationCompleted, userState);
        }
        
        private void OnGet_Latest_AllOperationCompleted(object arg) {
            if ((this.Get_Latest_AllCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_Latest_AllCompleted(this, new Get_Latest_AllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.ypwater.com/")]
    public partial class TagSecondInfo {
        
        private int i_Cycle_IdField;
        
        private string i_Tag_IdField;
        
        private double i_Value_0Field;
        
        private double i_Value_1Field;
        
        /// <remarks/>
        public int I_Cycle_Id {
            get {
                return this.i_Cycle_IdField;
            }
            set {
                this.i_Cycle_IdField = value;
            }
        }
        
        /// <remarks/>
        public string I_Tag_Id {
            get {
                return this.i_Tag_IdField;
            }
            set {
                this.i_Tag_IdField = value;
            }
        }
        
        /// <remarks/>
        public double I_Value_0 {
            get {
                return this.i_Value_0Field;
            }
            set {
                this.i_Value_0Field = value;
            }
        }
        
        /// <remarks/>
        public double I_Value_1 {
            get {
                return this.i_Value_1Field;
            }
            set {
                this.i_Value_1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void Get_Latest_By_TagIdCompletedEventHandler(object sender, Get_Latest_By_TagIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_Latest_By_TagIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_Latest_By_TagIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TagSecondInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TagSecondInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void Get_Latest_By_TagIdsCompletedEventHandler(object sender, Get_Latest_By_TagIdsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_Latest_By_TagIdsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_Latest_By_TagIdsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TagSecondInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TagSecondInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void Get_Latest_AllCompletedEventHandler(object sender, Get_Latest_AllCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_Latest_AllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_Latest_AllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TagSecondInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TagSecondInfo[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591