//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMM.Analysis {
    
    
    public partial class DocRoute {
        
        /// <summary>
        /// Form1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm Form1;
        
        /// <summary>
        /// WebPanel_Item 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Infragistics.WebUI.Misc.WebPanel WebPanel_Item;
        
        /// <summary>
        /// WebPanel_Ros 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Infragistics.WebUI.Misc.WebPanel WebPanel_Ros;
        
        /// <summary>
        /// WebPanel_Mrp 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Infragistics.WebUI.Misc.WebPanel WebPanel_Mrp;
        
        /// <summary>
        /// WebPanel_Plan 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Infragistics.WebUI.Misc.WebPanel WebPanel_Plan;
        
        /// <summary>
        /// WebPanel_Order 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Infragistics.WebUI.Misc.WebPanel WebPanel_Order;
        
        /// <summary>
        /// WebPanel_Bor 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Infragistics.WebUI.Misc.WebPanel WebPanel_Bor;
        
        /// <summary>
        /// WebPanel_Pay 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Infragistics.WebUI.Misc.WebPanel WebPanel_Pay;
        
        /// <summary>
        /// WebPanel_Draw 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Infragistics.WebUI.Misc.WebPanel WebPanel_Draw;
        
        /// <summary>
        /// Webpanel_RTS 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Infragistics.WebUI.Misc.WebPanel Webpanel_RTS;
    }
}
