//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDE2OPC.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DDE2OPC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BrandTitle {
            get {
                object obj = ResourceManager.GetObject("BrandTitle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon bridge {
            get {
                object obj = ResourceManager.GetObject("bridge", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Bridges {
            get {
                object obj = ResourceManager.GetObject("Bridges", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDE Item.
        /// </summary>
        internal static string ColumnHeader_DDE_Item_Text {
            get {
                return ResourceManager.GetString("ColumnHeader_DDE_Item_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDE Topic.
        /// </summary>
        internal static string ColumnHeader_DDE_Topic_Text {
            get {
                return ResourceManager.GetString("ColumnHeader_DDE_Topic_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPC 地址.
        /// </summary>
        internal static string ColumnHeader_OPC_Address_Text {
            get {
                return ResourceManager.GetString("ColumnHeader_OPC_Address_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 描述.
        /// </summary>
        internal static string ColumnHeader_Remark_Text {
            get {
                return ResourceManager.GetString("ColumnHeader_Remark_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 状态.
        /// </summary>
        internal static string ColumnHeader_Status_Text {
            get {
                return ResourceManager.GetString("ColumnHeader_Status_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 值.
        /// </summary>
        internal static string ColumnHeader_Value_Text {
            get {
                return ResourceManager.GetString("ColumnHeader_Value_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap control_play {
            get {
                object obj = ResourceManager.GetObject("control_play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap control_stop {
            get {
                object obj = ResourceManager.GetObject("control_stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建.
        /// </summary>
        internal static string FormMap_toolStrip_Map_Add {
            get {
                return ResourceManager.GetString("FormMap_toolStrip_Map_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        internal static string FormMap_toolStrip_Map_Delete {
            get {
                return ResourceManager.GetString("FormMap_toolStrip_Map_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改.
        /// </summary>
        internal static string FormMap_toolStrip_Map_Update {
            get {
                return ResourceManager.GetString("FormMap_toolStrip_Map_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;C.取消.
        /// </summary>
        internal static string FormMapInput_Button_Cancel_Text {
            get {
                return ResourceManager.GetString("FormMapInput_Button_Cancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Y.确定.
        /// </summary>
        internal static string FormMapInput_Button_OK_Text {
            get {
                return ResourceManager.GetString("FormMapInput_Button_OK_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDE&amp;OPC的映射关系.
        /// </summary>
        internal static string FormMapInput_GroupBox_Map_Text {
            get {
                return ResourceManager.GetString("FormMapInput_GroupBox_Map_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDE 项：.
        /// </summary>
        internal static string FormMapInput_Label_DDEItem_Text {
            get {
                return ResourceManager.GetString("FormMapInput_Label_DDEItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDE 标题：.
        /// </summary>
        internal static string FormMapInput_Label_DDETopic_Text {
            get {
                return ResourceManager.GetString("FormMapInput_Label_DDETopic_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPC 地址：.
        /// </summary>
        internal static string FormMapInput_Label_OPCAddress_Text {
            get {
                return ResourceManager.GetString("FormMapInput_Label_OPCAddress_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 备注：.
        /// </summary>
        internal static string FormMapInput_Label_Remark_Text {
            get {
                return ResourceManager.GetString("FormMapInput_Label_Remark_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap link {
            get {
                object obj = ResourceManager.GetObject("link", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap link_break {
            get {
                object obj = ResourceManager.GetObject("link_break", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap link_error {
            get {
                object obj = ResourceManager.GetObject("link_error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap link_go {
            get {
                object obj = ResourceManager.GetObject("link_go", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 失败.
        /// </summary>
        internal static string MapInfo_Status_Start_Failed_Text {
            get {
                return ResourceManager.GetString("MapInfo_Status_Start_Failed_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动.
        /// </summary>
        internal static string MapInfo_Status_Start_Success_Text {
            get {
                return ResourceManager.GetString("MapInfo_Status_Start_Success_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认.
        /// </summary>
        internal static string Message_ConfirmDeleteCaption {
            get {
                return ResourceManager.GetString("Message_ConfirmDeleteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您是否确定要删除？.
        /// </summary>
        internal static string Message_ConfirmDeleteText {
            get {
                return ResourceManager.GetString("Message_ConfirmDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请先选中一条记录!.
        /// </summary>
        internal static string Message_PleaseSelectItem {
            get {
                return ResourceManager.GetString("Message_PleaseSelectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sc_hover {
            get {
                object obj = ResourceManager.GetObject("sc_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sc_rest {
            get {
                object obj = ResourceManager.GetObject("sc_rest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tag {
            get {
                object obj = ResourceManager.GetObject("tag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tag_blue {
            get {
                object obj = ResourceManager.GetObject("tag_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tag_blue_add {
            get {
                object obj = ResourceManager.GetObject("tag_blue_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tag_blue_delete {
            get {
                object obj = ResourceManager.GetObject("tag_blue_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tag_blue_edit {
            get {
                object obj = ResourceManager.GetObject("tag_blue_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon tag_blue_icon {
            get {
                object obj = ResourceManager.GetObject("tag_blue_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
