//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.18444 版自动生成。
// 
#pragma warning disable 1591

namespace Shmzh.Monitor.Data.TagGatherService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TagGatherSoap", Namespace="http://shuizhi.ypwater.org/DataService/")]
    public partial class TagGather : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetByTagIdOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TagGather() {
            this.Url = global::Shmzh.Monitor.Data.Properties.Settings.Default.Shmzh_Monitor_Data_TagGatherService_TagGather;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetByTagIdCompletedEventHandler GetByTagIdCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://shuizhi.ypwater.org/DataService/GetByTagId", RequestNamespace="http://shuizhi.ypwater.org/DataService/", ResponseNamespace="http://shuizhi.ypwater.org/DataService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TagGatherInfo[] GetByTagId(string tagId) {
            object[] results = this.Invoke("GetByTagId", new object[] {
                        tagId});
            return ((TagGatherInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetByTagIdAsync(string tagId) {
            this.GetByTagIdAsync(tagId, null);
        }
        
        /// <remarks/>
        public void GetByTagIdAsync(string tagId, object userState) {
            if ((this.GetByTagIdOperationCompleted == null)) {
                this.GetByTagIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetByTagIdOperationCompleted);
            }
            this.InvokeAsync("GetByTagId", new object[] {
                        tagId}, this.GetByTagIdOperationCompleted, userState);
        }
        
        private void OnGetByTagIdOperationCompleted(object arg) {
            if ((this.GetByTagIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetByTagIdCompleted(this, new GetByTagIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://shuizhi.ypwater.org/DataService/")]
    public partial class TagGatherInfo {
        
        private string i_TAG_IDField;
        
        private string i_DESIGN_CDField;
        
        private string i_ADDRESSField;
        
        private double i_PARA_AField;
        
        private double i_PARA_BField;
        
        private double i_PARA_CField;
        
        private double i_MAXField;
        
        private double i_MINField;
        
        private short i_ACTIONField;
        
        /// <remarks/>
        public string I_TAG_ID {
            get {
                return this.i_TAG_IDField;
            }
            set {
                this.i_TAG_IDField = value;
            }
        }
        
        /// <remarks/>
        public string I_DESIGN_CD {
            get {
                return this.i_DESIGN_CDField;
            }
            set {
                this.i_DESIGN_CDField = value;
            }
        }
        
        /// <remarks/>
        public string I_ADDRESS {
            get {
                return this.i_ADDRESSField;
            }
            set {
                this.i_ADDRESSField = value;
            }
        }
        
        /// <remarks/>
        public double I_PARA_A {
            get {
                return this.i_PARA_AField;
            }
            set {
                this.i_PARA_AField = value;
            }
        }
        
        /// <remarks/>
        public double I_PARA_B {
            get {
                return this.i_PARA_BField;
            }
            set {
                this.i_PARA_BField = value;
            }
        }
        
        /// <remarks/>
        public double I_PARA_C {
            get {
                return this.i_PARA_CField;
            }
            set {
                this.i_PARA_CField = value;
            }
        }
        
        /// <remarks/>
        public double I_MAX {
            get {
                return this.i_MAXField;
            }
            set {
                this.i_MAXField = value;
            }
        }
        
        /// <remarks/>
        public double I_MIN {
            get {
                return this.i_MINField;
            }
            set {
                this.i_MINField = value;
            }
        }
        
        /// <remarks/>
        public short I_ACTION {
            get {
                return this.i_ACTIONField;
            }
            set {
                this.i_ACTIONField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetByTagIdCompletedEventHandler(object sender, GetByTagIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetByTagIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetByTagIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TagGatherInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TagGatherInfo[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591